apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-application
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/wordpress-application