apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-content
  labels:
    type: local
spec:
  storageClassName: wordpress-content
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/wordpress-content
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content
spec:
  storageClassName: wordpress-content
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi