apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-content
  labels:
    type: local
spec:
  storageClassName: wordpress-content
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/wordpress-content