apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-mysql
  labels:
    type: local
spec:
  storageClassName: hostpath-mysql
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mysql